import { getAllPosts, getPostBySlug } from '@/db/posts';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import Link from 'next/link';
import PostCard from '@/components/PostCard';
import ArticleEngagementTracker from '@/components/ArticleEngagementTracker';
import { getRecommendations } from '@/agents/recommendationAgent';
import { formatDate, getCategoryMeta, getReadingTime, getTrustSignals } from '@/lib/postPresentation';
import { Post } from '@/types';

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';

export const dynamic = 'force-dynamic';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(slug);

  if (!post) return { title: 'Post Not Found' };

  return {
    title: post.title,
    description: post.metaDescription || post.summary,
    openGraph: {
      title: post.title,
      description: post.metaDescription || post.summary,
      type: 'article',
      url: `${BASE_URL}/post/${post.slug}`,
    },
    alternates: {
      canonical: `${BASE_URL}/post/${post.slug}`,
    },
  };
}

export default async function PostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = getPostBySlug(slug);

  if (!post) {
    notFound();
  }

  const readingTime = getReadingTime(post.content);
  const meta = getCategoryMeta(post.category);
  const trustSignals = getTrustSignals(post);
  const { posts: allPosts } = getAllPosts(1, 500);
  const related = getRecommendations(post, allPosts, 3)
    .map((item) => allPosts.find((candidate) => candidate.id === item.id))
    .filter((candidate): candidate is Post => Boolean(candidate));

  return (
    <article style={{ maxWidth: 'var(--content-width)', margin: '0 auto', padding: '2rem 1rem' }}>
      <ArticleEngagementTracker slug={post.slug} category={post.category} tags={post.tags} />

      {/* Breadcrumb */}
      <nav style={{ marginBottom: '1.5rem', fontSize: '0.8rem', color: 'var(--color-text-muted)' }}>
        <Link href="/" style={{ color: 'var(--color-accent)', textDecoration: 'none' }}>Home</Link>
        <span style={{ margin: '0 0.5rem' }}>/</span>
        <Link href={`/category/${post.category}`} style={{ color: 'var(--color-accent)', textDecoration: 'none' }}>
          {meta.label}
        </Link>
        <span style={{ margin: '0 0.5rem' }}>/</span>
        <span style={{ color: 'var(--color-text-secondary)' }}>{post.title}</span>
      </nav>

      {/* Header */}
      <header style={{ marginBottom: '2rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem', flexWrap: 'wrap' }}>
          <span className={`category-badge category-badge-${post.category}`}>
            {meta.label}
          </span>
          {post.autoGenerated && (
            <span style={{ fontSize: '0.7rem', color: 'var(--color-text-muted)' }}>AI Generated</span>
          )}
        </div>

        <h1 style={{
          fontFamily: 'var(--font-headline)',
          fontSize: 'clamp(1.75rem, 4vw, 2.5rem)',
          fontWeight: 700,
          lineHeight: 1.15,
          marginBottom: '1rem',
          color: 'var(--color-text-primary)',
        }}>
          {post.title}
        </h1>

        <p style={{
          fontSize: '1.125rem',
          color: 'var(--color-text-secondary)',
          lineHeight: 1.6,
          marginBottom: '1rem',
        }}>
          {post.summary}
        </p>

        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: '1rem',
          fontSize: '0.85rem',
          color: 'var(--color-text-muted)',
          paddingBottom: '1rem',
          borderBottom: '2px solid var(--color-text-primary)',
        }}>
          <time>{formatDate(post.createdAt)}</time>
          <span>{readingTime} min read</span>
          <span>{post.autoGenerated ? 'By AI Correspondent' : 'Editorial'}</span>
        </div>
      </header>

      {/* Trust signals */}
      <div className="trust-panel">
        {trustSignals.map((signal) => (
          <div key={signal.label} className={`trust-card ${signal.tone}`}>
            <span>{signal.label}</span>
            <strong>{signal.value}</strong>
          </div>
        ))}
      </div>

      {/* Article body */}
      <div
        className="post-content"
        style={{ marginBottom: '2.5rem' }}
        dangerouslySetInnerHTML={{ __html: post.content }}
      />

      {/* Tags */}
      {post.tags.length > 0 && (
        <div style={{ borderTop: '1px solid var(--color-border)', paddingTop: '1.5rem', marginBottom: '2rem' }}>
          <h3 style={{
            fontSize: '0.75rem',
            fontWeight: 600,
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
            color: 'var(--color-text-muted)',
            marginBottom: '0.75rem',
          }}>
            Tags
          </h3>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
            {post.tags.map((tag) => (
              <Link
                key={tag}
                href={`/search?q=${encodeURIComponent(tag)}`}
                style={{
                  padding: '4px 12px',
                  fontSize: '0.8rem',
                  background: 'var(--color-bg-secondary)',
                  color: 'var(--color-text-secondary)',
                  borderRadius: 'var(--radius-full)',
                  textDecoration: 'none',
                }}
              >
                #{tag}
              </Link>
            ))}
          </div>
        </div>
      )}

      {/* Sources */}
      <div style={{ borderTop: '1px solid var(--color-border)', paddingTop: '1.5rem', marginBottom: '2rem' }}>
        <h3 style={{
          fontSize: '0.75rem',
          fontWeight: 600,
          textTransform: 'uppercase',
          letterSpacing: '0.05em',
          color: 'var(--color-text-muted)',
          marginBottom: '0.75rem',
        }}>
          Sources & References
        </h3>
        {post.sourceReferences.length > 0 ? (
          <ul style={{ fontSize: '0.875rem', color: 'var(--color-text-secondary)', paddingLeft: '1.25rem' }}>
            {post.sourceReferences.map((ref, i) => (
              <li key={`${ref}-${i}`} style={{ marginBottom: '0.375rem' }}>{ref}</li>
            ))}
          </ul>
        ) : (
          <p style={{ fontSize: '0.85rem', color: 'var(--color-text-muted)' }}>
            No external references stored. Treat as AI-assisted analysis.
          </p>
        )}
      </div>

      {/* Related articles */}
      {related.length > 0 && (
        <section className="content-section">
          <div className="section-heading">
            <h2>More from {meta.label}</h2>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '1.25rem' }}>
            {related.map((item, index) => (
              <PostCard key={item.id} post={item} index={index} compact />
            ))}
          </div>
        </section>
      )}

      {/* Back link */}
      <div style={{ borderTop: '1px solid var(--color-border)', paddingTop: '1.5rem', marginTop: '2rem' }}>
        <Link href="/" style={{ color: 'var(--color-accent)', fontSize: '0.875rem', fontWeight: 500, textDecoration: 'none' }}>
          ← Back to all articles
        </Link>
      </div>
    </article>
  );
}
