import { getPostBySlug, getAllPosts } from '@/db/posts';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import Link from 'next/link';

export const dynamic = 'force-dynamic';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(slug);

  if (!post) return { title: 'Post Not Found' };

  return {
    title: post.title,
    description: post.metaDescription,
    openGraph: {
      title: post.title,
      description: post.metaDescription,
      type: 'article',
      url: `http://localhost:3000/post/${post.slug}`,
    },
    alternates: {
      canonical: `http://localhost:3000/post/${post.slug}`,
    },
  };
}

export default async function PostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = getPostBySlug(slug);

  if (!post) {
    notFound();
  }

  return (
    <article className="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8">
      {/* Breadcrumb */}
      <nav className="mb-6 text-sm text-gray-500">
        <Link href="/" className="hover:text-gray-700">
          Home
        </Link>
        <span className="mx-2">/</span>
        <Link href={`/category/${post.category}`} className="hover:text-gray-700">
          {post.category.charAt(0).toUpperCase() + post.category.slice(1)}
        </Link>
        <span className="mx-2">/</span>
        <span className="text-gray-700">{post.title}</span>
      </nav>

      {/* Header */}
      <header className="mb-8">
        <div className="flex items-center gap-2 mb-4">
          <span
            className={`rounded-full px-3 py-1 text-xs font-medium ${
              post.category === 'blog'
                ? 'bg-blue-100 text-blue-800'
                : 'bg-red-100 text-red-800'
            }`}
          >
            {post.category === 'blog' ? '📝 Blog' : '📰 News'}
          </span>
          {post.autoGenerated && (
            <span className="rounded-full bg-green-100 px-3 py-1 text-xs font-medium text-green-800">
              🤖 Auto Generated
            </span>
          )}
        </div>

        <h1 className="text-3xl font-bold text-gray-900 mb-4 leading-tight">
          {post.title}
        </h1>

        <p className="text-lg text-gray-600 mb-4">{post.summary}</p>

        <div className="flex items-center gap-4 text-sm text-gray-500">
          <time>
            {new Date(post.createdAt).toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })}
          </time>
        </div>
      </header>

      {/* Content */}
      <div
        className="prose prose-lg max-w-none mb-8"
        dangerouslySetInnerHTML={{ __html: post.content }}
      />

      {/* Tags */}
      {post.tags.length > 0 && (
        <div className="border-t border-gray-200 pt-6 mb-6">
          <h3 className="text-sm font-medium text-gray-500 mb-2">Tags</h3>
          <div className="flex flex-wrap gap-2">
            {post.tags.map((tag) => (
              <span
                key={tag}
                className="rounded-full bg-gray-100 px-3 py-1 text-sm text-gray-600"
              >
                {tag}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* References */}
      {post.sourceReferences.length > 0 && (
        <div className="border-t border-gray-200 pt-6 mb-6">
          <h3 className="text-sm font-medium text-gray-500 mb-2">Sources & References</h3>
          <ul className="list-disc list-inside text-sm text-gray-600 space-y-1">
            {post.sourceReferences.map((ref, i) => (
              <li key={i}>{ref}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Back link */}
      <div className="border-t border-gray-200 pt-6">
        <Link href="/" className="text-blue-600 hover:text-blue-800 text-sm font-medium">
          ← Back to all posts
        </Link>
      </div>
    </article>
  );
}
