import { getAllPosts, getPostBySlug } from '@/db/posts';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import Link from 'next/link';
import PostCard from '@/components/PostCard';
import ArticleEngagementTracker from '@/components/ArticleEngagementTracker';
import { getRecommendations } from '@/agents/recommendationAgent';
import { formatDate, getCategoryMeta, getReadingTime, getTrustSignals } from '@/lib/postPresentation';
import { Post } from '@/types';

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';

export const dynamic = 'force-dynamic';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(slug);

  if (!post) return { title: 'Post Not Found' };

  return {
    title: post.title,
    description: post.metaDescription || post.summary,
    openGraph: {
      title: post.title,
      description: post.metaDescription || post.summary,
      type: 'article',
      url: `${BASE_URL}/post/${post.slug}`,
    },
    alternates: {
      canonical: `${BASE_URL}/post/${post.slug}`,
    },
  };
}

export default async function PostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = getPostBySlug(slug);

  if (!post) {
    notFound();
  }

  const readingTime = getReadingTime(post.content);
  const meta = getCategoryMeta(post.category);
  const trustSignals = getTrustSignals(post);
  const { posts: allPosts } = getAllPosts(1, 500);
  const related = getRecommendations(post, allPosts, 3)
    .map((item) => allPosts.find((candidate) => candidate.id === item.id))
    .filter((candidate): candidate is Post => Boolean(candidate));

  return (
    <article className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
      <ArticleEngagementTracker slug={post.slug} category={post.category} tags={post.tags} />

      <nav className="mb-6 text-sm animate-fade-in" style={{ color: 'var(--text-muted)' }}>
        <Link href="/" className="transition-colors" style={{ color: 'var(--text-accent)' }}>
          Home
        </Link>
        <span className="mx-2">/</span>
        <Link href={`/category/${post.category}`} className="transition-colors" style={{ color: 'var(--text-accent)' }}>
          {meta.label}
        </Link>
        <span className="mx-2">/</span>
        <span style={{ color: 'var(--text-secondary)' }}>{post.title}</span>
      </nav>

      <header className="mb-8 animate-fade-in-up">
        <div className="flex items-center gap-2 mb-4 flex-wrap">
          <span className="badge" style={{ color: meta.color, background: 'rgba(255,255,255,0.05)' }}>
            {meta.icon} {meta.label}
          </span>
          {post.autoGenerated && <span className="badge badge-auto">AI Assisted</span>}
          {post.sourceReferences.length > 0 && (
            <span className="badge badge-source">Sources {post.sourceReferences.length}</span>
          )}
        </div>

        <h1 className="text-3xl sm:text-4xl font-bold mb-4 leading-tight" style={{ color: 'var(--text-primary)' }}>
          {post.title}
        </h1>

        <p className="text-lg mb-4" style={{ color: 'var(--text-secondary)', lineHeight: '1.7' }}>
          {post.summary}
        </p>

        <div className="flex flex-wrap items-center gap-4 text-sm" style={{ color: 'var(--text-muted)' }}>
          <time>{formatDate(post.createdAt)}</time>
          <span>{readingTime} min read</span>
          <span>{post.autoGenerated ? 'Generated by the AI newsroom pipeline' : 'Editorial article'}</span>
        </div>
      </header>

      <div className="trust-panel">
        {trustSignals.map((signal) => (
          <div key={signal.label} className={`trust-card ${signal.tone}`}>
            <span>{signal.label}</span>
            <strong>{signal.value}</strong>
          </div>
        ))}
      </div>

      <div
        className="mb-8"
        style={{
          height: '2px',
          background: 'linear-gradient(to right, var(--border-accent), transparent)',
          borderRadius: '1px',
        }}
      />

      <div className="post-content mb-8 animate-fade-in-up" style={{ animationDelay: '0.15s' }} dangerouslySetInnerHTML={{ __html: post.content }} />

      {post.tags.length > 0 && (
        <div className="pt-6 mb-6" style={{ borderTop: '1px solid var(--border-subtle)' }}>
          <h3 className="text-sm font-medium mb-3" style={{ color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            Tags
          </h3>
          <div className="flex flex-wrap gap-2">
            {post.tags.map((tag) => (
              <span key={tag} className="badge" style={{ background: 'rgba(255,255,255,0.05)', color: 'var(--text-secondary)' }}>
                #{tag}
              </span>
            ))}
          </div>
        </div>
      )}

      <div className="pt-6 mb-8" style={{ borderTop: '1px solid var(--border-subtle)' }}>
        <h3 className="text-sm font-medium mb-3" style={{ color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Sources and References
        </h3>
        {post.sourceReferences.length > 0 ? (
          <ul className="space-y-2 text-sm" style={{ color: 'var(--text-secondary)' }}>
            {post.sourceReferences.map((ref, i) => (
              <li key={`${ref}-${i}`} className="flex items-start gap-2">
                <span style={{ color: 'var(--text-accent)' }}>-</span>
                <span>{ref}</span>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-sm" style={{ color: 'var(--text-muted)' }}>
            No external references were stored for this article. Treat this post as AI-assisted analysis and verify important claims independently.
          </p>
        )}
      </div>

      {related.length > 0 && (
        <section className="content-section">
          <div className="section-heading">
            <div>
              <p>Continue reading</p>
              <h2>Related Articles</h2>
            </div>
          </div>
          <div className="grid gap-6 md:grid-cols-3">
            {related.map((item, index) => (
              <PostCard key={item.id} post={item} index={index} compact />
            ))}
          </div>
        </section>
      )}

      <div className="pt-6 mt-8" style={{ borderTop: '1px solid var(--border-subtle)' }}>
        <Link href="/" className="inline-flex items-center gap-1 text-sm font-medium transition-colors" style={{ color: 'var(--text-accent)' }}>
          <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back to all posts
        </Link>
      </div>
    </article>
  );
}
