import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About — AI Auto News',
  description: 'Learn about the AI Auto News autonomous publishing platform.',
};

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-6">About AI Auto News</h1>

      <div className="prose prose-lg max-w-none">
        <p>
          <strong>AI Auto News</strong> is an autonomous AI-powered publishing platform that
          researches trending topics, generates high-quality content, and publishes it
          automatically — every 5 minutes.
        </p>

        <h2>🧠 How It Works</h2>
        <p>
          The platform operates like a mini autonomous newsroom powered by AI agents:
        </p>
        <ol>
          <li>
            <strong>Research Agent</strong> — Queries real-world trending AI and tech topics
            using the Perplexity API, extracting structured insights and references.
          </li>
          <li>
            <strong>Blog Agent</strong> — Generates comprehensive, SEO-optimized blog posts
            using the Gemini API with professional tech journalist tone.
          </li>
          <li>
            <strong>News Agent</strong> — Creates concise breaking-news style articles with
            clear headlines and sharp reporting.
          </li>
          <li>
            <strong>Formatting Agent</strong> — Cleans and standardizes all content into
            proper HTML format, removing artifacts and ensuring consistency.
          </li>
          <li>
            <strong>Autonomous Publisher</strong> — Orchestrates the entire pipeline every 5
            minutes: research → generate → format → save → publish.
          </li>
        </ol>

        <h2>🏗 Architecture</h2>
        <ul>
          <li><strong>Framework:</strong> Next.js (App Router) with TypeScript</li>
          <li><strong>Styling:</strong> TailwindCSS</li>
          <li><strong>Database:</strong> SQLite (better-sqlite3)</li>
          <li><strong>AI:</strong> Gemini API + Perplexity API</li>
          <li><strong>Auth:</strong> JWT-based admin authentication</li>
          <li><strong>Scheduler:</strong> In-app setInterval with lock mechanism</li>
        </ul>

        <h2>🔄 Automation</h2>
        <p>
          The auto-publisher starts automatically when the app boots. It runs entirely within
          the Next.js runtime — no external schedulers, no cron jobs, no separate services.
          The system includes duplicate prevention, error handling, and retry logic to ensure
          reliable operation.
        </p>

        <h2>⚡ Features</h2>
        <ul>
          <li>Automatic content generation every 5 minutes</li>
          <li>Real-world data collection via Perplexity API</li>
          <li>AI content generation via Gemini API</li>
          <li>SEO metadata for every post</li>
          <li>Category filtering (Blog / News)</li>
          <li>Admin dashboard with manual controls</li>
          <li>Duplicate topic prevention</li>
          <li>Graceful error handling</li>
        </ul>

        <h2>⚠️ Disclaimer</h2>
        <p>
          All content on this platform is generated by AI. While the system strives for
          accuracy and quality, AI-generated content may contain errors or outdated
          information. Always verify important information from primary sources.
        </p>
      </div>
    </div>
  );
}
