import { researchAgent } from './researchAgent';
import { blogAgent } from './blogAgent';
import { newsAgent } from './newsAgent';
import { formattingAgent } from './formattingAgent';
import { createPost, slugExists, getRecentTopics } from '@/db/posts';

export async function autonomousPublisher(): Promise<{ success: boolean; message: string }> {
  try {
    console.log('[AutoPublisher] Starting content generation cycle...');

    // Step 1: Get recent topics to avoid duplicates
    const recentTopics = getRecentTopics(10);

    // Step 2: Research
    console.log('[AutoPublisher] Researching trending topics...');
    const research = await researchAgent(recentTopics);

    if (!research.topic && !research.headline) {
      return { success: false, message: 'Research returned empty results' };
    }

    // Step 3: Decide blog or news (alternate)
    const isBlog = Math.random() > 0.4; // 60% blogs, 40% news
    const category = isBlog ? 'blog' : 'news';

    console.log(`[AutoPublisher] Generating ${category} content...`);

    // Step 4: Generate content
    const generated = isBlog
      ? await blogAgent(research)
      : await newsAgent(research);

    if (!generated.title || !generated.content) {
      return { success: false, message: 'Content generation returned empty results' };
    }

    // Step 5: Format content
    console.log('[AutoPublisher] Formatting content...');
    const formattedContent = formattingAgent(generated.content);

    // Step 6: Ensure unique slug
    let slug = generated.slug || generated.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    slug = slug.substring(0, 80);

    if (slugExists(slug)) {
      slug = `${slug}-${Date.now()}`;
    }

    // Step 7: Save to database
    console.log('[AutoPublisher] Saving to database...');
    const post = createPost({
      title: generated.title,
      slug,
      content: formattedContent,
      summary: generated.summary,
      tags: generated.tags,
      category,
      metaDescription: generated.metaDescription,
      sourceReferences: research.references,
      autoGenerated: true,
    });

    console.log(`[AutoPublisher] Successfully published: "${post.title}" (${category})`);
    return { success: true, message: `Published: ${post.title}` };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.error('[AutoPublisher] Error:', message);
    return { success: false, message };
  }
}
