import { researchAgent } from './researchAgent';
import { blogAgent } from './blogAgent';
import { newsAgent } from './newsAgent';
import { formattingAgent } from './formattingAgent';
import { createPost, slugExists, getRecentTopics } from '@/db/posts';
import { logger } from '@/lib/logger';
import { APP_CONFIG } from '@/lib/config';

function decideCategory(): 'blog' | 'news' {
  const strategy = APP_CONFIG.contentStrategy;

  if (strategy === 'blog-heavy') return 'blog';
  if (strategy === 'news-heavy') return 'news';
  if (strategy === 'research-only') return 'blog'; // research-only still produces blog-formatted content

  // balanced: 60% blog, 40% news
  return Math.random() > 0.4 ? 'blog' : 'news';
}

export async function autonomousPublisher(): Promise<{ success: boolean; message: string }> {
  const startTime = Date.now();
  const cycleId = `pub-${Date.now()}`;

  try {
    logger.info('[AutoPublisher] Starting content generation cycle', { cycleId, strategy: APP_CONFIG.contentStrategy });

    // Step 1: Get recent topics to avoid duplicates
    const recentTopics = getRecentTopics(10);
    logger.debug('[AutoPublisher] Loaded recent topics', { count: recentTopics.length });

    // Step 2: Research
    const researchStart = Date.now();
    logger.info('[AutoPublisher] Researching trending topics...');
    const research = await researchAgent(recentTopics);
    const researchDuration = Date.now() - researchStart;

    if (!research.topic && !research.headline) {
      logger.warn('[AutoPublisher] Research returned empty results', { cycleId });
      return { success: false, message: 'Research returned empty results' };
    }

    logger.info('[AutoPublisher] Research completed', {
      topic: research.topic,
      duration: researchDuration,
    });

    // Step 3: Decide blog or news
    const category = decideCategory();
    logger.info('[AutoPublisher] Content type decided', { category });

    // Step 4: Generate content
    const generateStart = Date.now();
    const generated = category === 'blog'
      ? await blogAgent(research)
      : await newsAgent(research);
    const generateDuration = Date.now() - generateStart;

    if (!generated.title || !generated.content) {
      logger.warn('[AutoPublisher] Content generation returned empty results', { cycleId, category });
      return { success: false, message: 'Content generation returned empty results' };
    }

    logger.info('[AutoPublisher] Content generated', {
      title: generated.title,
      wordCount: generated.content.split(/\s+/).length,
      duration: generateDuration,
    });

    // Step 5: Format content
    const formattedContent = formattingAgent(generated.content);

    // Step 6: Ensure unique slug
    let slug = generated.slug || generated.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    slug = slug.substring(0, 80);

    if (slugExists(slug)) {
      slug = `${slug}-${Date.now()}`;
      logger.debug('[AutoPublisher] Slug collision, appended timestamp', { slug });
    }

    // Step 7: Save to database
    const post = createPost({
      title: generated.title,
      slug,
      content: formattedContent,
      summary: generated.summary,
      tags: generated.tags,
      category,
      metaDescription: generated.metaDescription,
      sourceReferences: research.references,
      autoGenerated: true,
    });

    const totalDuration = Date.now() - startTime;
    logger.info('[AutoPublisher] Successfully published', {
      cycleId,
      postId: post.id,
      title: post.title,
      category,
      totalDuration,
    });

    return { success: true, message: `Published: ${post.title}` };
  } catch (error) {
    const totalDuration = Date.now() - startTime;
    const message = error instanceof Error ? error.message : 'Unknown error';
    logger.error('[AutoPublisher] Cycle failed', error instanceof Error ? error : undefined, {
      cycleId,
      totalDuration,
    });
    return { success: false, message };
  }
}
