// ─────────────────────────────────────────────────────────────────────────────
// PublisherAgent — saves a validated article to the database.
// Handles slug generation, dedup, and sanitization.
// ─────────────────────────────────────────────────────────────────────────────

import DOMPurify from 'isomorphic-dompurify';
import { v4 as uuidv4 } from 'uuid';
import { AgentLogger } from '@/lib/agentLogger';
import getDb from '@/db/index';
import type { RawArticle } from './writerAgent';

/**
 * publisherAgent — saves an article to the posts table.
 *
 * @param runId - Unique ID for this generation run
 * @param article - The validated article from WriterAgent
 * @param qualityScore - Score from QualityAgent (0-100)
 * @returns The ID of the newly created post
 * @throws {Error} If DB insert fails
 */
export async function publisherAgent(
  runId: string,
  article: RawArticle,
  qualityScore: number,
): Promise<string> {
  const log = new AgentLogger(runId, 'PublisherAgent');

  // Generate unique slug
  let slug = article.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80);

  // Check for slug collision
  const db = getDb();
  const existing = db.prepare('SELECT id FROM posts WHERE slug = ?').get(slug);
  if (existing) {
    slug = `${slug}-${Date.now().toString(36)}`;
    log.debug('Slug collision, appended timestamp', { slug });
  }

  // Sanitize HTML content
  const sanitizedContent = DOMPurify.sanitize(article.content, {
    ALLOWED_TAGS: [
      'h1', 'h2', 'h3', 'h4', 'p', 'ul', 'ol', 'li', 'strong', 'em',
      'a', 'br', 'blockquote', 'code', 'pre', 'table', 'thead', 'tbody',
      'tr', 'th', 'td',
    ],
    ALLOWED_ATTR: ['href', 'target', 'rel'],
  });

  const id = uuidv4();
  const now = new Date().toISOString();

  db.prepare(`
    INSERT INTO posts (id, title, slug, content, summary, tags, category, metaDescription, createdAt, updatedAt, sourceReferences, autoGenerated)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `).run(
    id,
    article.title,
    slug,
    sanitizedContent,
    article.excerpt,
    JSON.stringify(article.tags.slice(0, 8)),
    article.category.toLowerCase(),
    article.excerpt.slice(0, 160),
    now,
    now,
    JSON.stringify([article.sourceTopic]),
    1,
  );

  log.info(`✅ Published article`, {
    id,
    slug,
    title: article.title,
    category: article.category,
    template: article.templateId,
    qualityScore,
    model: article.geminiModelUsed,
  });

  return id;
}
