import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ConfigBanner from '@/components/ConfigBanner';

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';
const inter = Inter({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: 'TechPulse AI — Autonomous AI Journalism',
    template: '%s | TechPulse AI',
  },
  description:
    'Autonomous AI-powered Tech & AI news platform. Real-time coverage generated by AI agents using Gemini.',
  openGraph: {
    title: 'TechPulse AI',
    description: 'Autonomous AI journalism for the tech world.',
    type: 'website',
    url: BASE_URL,
  },
  alternates: {
    canonical: BASE_URL,
    types: {
      'application/rss+xml': `${BASE_URL}/rss.xml`,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased min-h-screen flex flex-col`}
        style={{ background: 'var(--color-bg)', color: 'var(--color-text-primary)' }}
      >
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:rounded-lg focus:font-semibold"
          style={{ background: 'var(--color-accent)', color: 'white' }}
        >
          Skip to content
        </a>
        <ConfigBanner />
        <Header />
        <main id="main-content" className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
