'use client';

import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';

interface PostItem {
  id: string;
  title: string;
  slug: string;
  content: string;
  summary: string;
  tags: string[];
  metaDescription: string;
  sourceReferences: string[];
  category: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

interface Stats {
  total: number;
  autoCount: number;
  lastGeneration: string | null;
  scheduler: {
    running: boolean;
    lastRun: string | null;
    totalGenerated: number;
  };
}

interface AgentLog {
  id: number;
  run_id: string;
  agent_name: string;
  level: string;
  message: string;
  metadata: string | null;
  created_at: string;
}

export default function AdminPage() {
  const [loggedIn, setLoggedIn] = useState(false);
  const [checkingAuth, setCheckingAuth] = useState(true);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loginError, setLoginError] = useState('');
  const [stats, setStats] = useState<Stats | null>(null);
  const [posts, setPosts] = useState<PostItem[]>([]);
  const [logs, setLogs] = useState<AgentLog[]>([]);
  const [generating, setGenerating] = useState(false);
  const [message, setMessage] = useState('');

  useEffect(() => {
    fetch('/api/auth')
      .then((res) => { if (res.ok) setLoggedIn(true); })
      .catch(() => {})
      .finally(() => setCheckingAuth(false));
  }, []);

  const fetchData = useCallback(async () => {
    try {
      const [statsRes, postsRes] = await Promise.all([
        fetch('/api/admin'),
        fetch('/api/posts?limit=50'),
      ]);

      if (statsRes.status === 401) { setLoggedIn(false); return; }
      if (statsRes.ok) setStats(await statsRes.json());
      if (postsRes.ok) {
        const data = await postsRes.json();
        setPosts(data.posts || []);
      }

      // Fetch agent logs
      try {
        const logsRes = await fetch('/api/admin/logs?limit=50');
        if (logsRes.ok) {
          const logsData = await logsRes.json();
          setLogs(logsData.logs || []);
        }
      } catch { /* non-fatal */ }
    } catch { /* retry on next interval */ }
  }, []);

  useEffect(() => {
    if (!loggedIn) return;
    fetchData();
    const interval = setInterval(fetchData, 15000);
    const handleVisibility = () => { if (document.visibilityState === 'visible') fetchData(); };
    document.addEventListener('visibilitychange', handleVisibility);
    return () => { clearInterval(interval); document.removeEventListener('visibilitychange', handleVisibility); };
  }, [loggedIn, fetchData]);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoginError('');
    try {
      const res = await fetch('/api/auth', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password }),
      });
      if (res.ok) setLoggedIn(true);
      else setLoginError('Invalid credentials');
    } catch { setLoginError('Login failed'); }
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setMessage('');
    try {
      const res = await fetch('/api/generate', { method: 'POST' });
      const data = await res.json();
      setMessage(data.success ? `✅ ${data.message}` : `❌ ${data.message || 'Generation failed'}`);
      fetchData();
    } catch { setMessage('❌ Failed to generate content'); }
    finally { setGenerating(false); }
  };

  const handleToggleScheduler = async () => {
    try {
      const res = await fetch('/api/scheduler', { method: 'POST' });
      const data = await res.json();
      setMessage(data.running ? '▶️ Scheduler started' : '⏸ Scheduler paused');
      fetchData();
    } catch { setMessage('❌ Failed to toggle scheduler'); }
  };

  const handleDelete = async (slug: string) => {
    if (!confirm('Delete this post?')) return;
    try {
      const res = await fetch(`/api/posts/${slug}`, { method: 'DELETE' });
      if (res.ok) { setMessage('🗑️ Post deleted'); fetchData(); }
      else setMessage('❌ Failed to delete');
    } catch { setMessage('❌ Failed to delete'); }
  };

  if (checkingAuth) {
    return (
      <div style={{ maxWidth: '400px', margin: '4rem auto', padding: '0 1rem', textAlign: 'center' }}>
        <p style={{ color: 'var(--color-text-muted)' }}>Checking authentication...</p>
      </div>
    );
  }

  if (!loggedIn) {
    return (
      <div style={{ maxWidth: '400px', margin: '4rem auto', padding: '0 1rem' }}>
        <div className="admin-card">
          <div style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
            <div style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>🔐</div>
            <h1 style={{ fontFamily: 'var(--font-headline)', fontSize: '1.5rem', marginBottom: '0.25rem' }}>Admin Login</h1>
            <p style={{ color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>Manage your publishing platform</p>
          </div>
          <form onSubmit={handleLogin} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div>
              <label htmlFor="admin-username" style={{ display: 'block', fontSize: '0.85rem', fontWeight: 500, marginBottom: '0.375rem', color: 'var(--color-text-secondary)' }}>Username</label>
              <input id="admin-username" type="text" value={username} onChange={(e) => setUsername(e.target.value)} className="search-input" required />
            </div>
            <div>
              <label htmlFor="admin-password" style={{ display: 'block', fontSize: '0.85rem', fontWeight: 500, marginBottom: '0.375rem', color: 'var(--color-text-secondary)' }}>Password</label>
              <input id="admin-password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="search-input" required />
            </div>
            {loginError && <p style={{ color: '#DC2626', fontSize: '0.85rem' }}>{loginError}</p>}
            <button type="submit" className="btn-primary" style={{ width: '100%', justifyContent: 'center' }}>Sign In</button>
          </form>
        </div>
      </div>
    );
  }

  // ── Dashboard ─────────────────────────────────────────────────────────────
  return (
    <div style={{ maxWidth: 'var(--max-width)', margin: '0 auto', padding: '2rem 1rem' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '2rem' }}>
        <div>
          <h1 style={{ fontFamily: 'var(--font-headline)', fontSize: '1.75rem', fontWeight: 700 }}>Admin Dashboard</h1>
          <p style={{ color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>Manage your autonomous publishing platform</p>
        </div>
        <button onClick={() => setLoggedIn(false)} className="btn-ghost" style={{ fontSize: '0.8rem' }}>Logout</button>
      </div>

      {message && (
        <div role="status" aria-live="polite" className="admin-card" style={{ marginBottom: '1.5rem', fontSize: '0.875rem' }}>
          {message}
        </div>
      )}

      {/* Stats */}
      {stats && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '1rem', marginBottom: '1.5rem' }}>
          <div className="stat-card">
            <div className="stat-value">{stats.total}</div>
            <div className="stat-label">Total Articles</div>
          </div>
          <div className="stat-card">
            <div className="stat-value">{stats.autoCount}</div>
            <div className="stat-label">AI Generated</div>
          </div>
          <div className="stat-card">
            <div style={{ fontSize: '0.9rem', fontWeight: 600 }}>
              {stats.lastGeneration ? new Date(stats.lastGeneration).toLocaleString() : 'Never'}
            </div>
            <div className="stat-label">Last Generation</div>
          </div>
          <div className="stat-card">
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', justifyContent: 'center' }}>
              <span className="pulse-dot" style={{ background: stats.scheduler.running ? '#059669' : '#DC2626' }} />
              <span style={{ fontSize: '0.9rem', fontWeight: 600, color: stats.scheduler.running ? '#059669' : '#DC2626' }}>
                {stats.scheduler.running ? 'Running' : 'Paused'}
              </span>
            </div>
            <div className="stat-label">Scheduler</div>
          </div>
        </div>
      )}

      {/* Actions */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.75rem', marginBottom: '2rem' }}>
        <button onClick={handleGenerate} disabled={generating} className="btn-primary" style={{ opacity: generating ? 0.6 : 1 }}>
          {generating ? '⏳ Generating...' : '✨ Generate Now'}
        </button>
        <button onClick={handleToggleScheduler} className="btn-ghost">
          {stats?.scheduler.running ? '⏸ Pause' : '▶️ Start'} Automation
        </button>
      </div>

      {/* Agent Logs */}
      <div className="admin-card" style={{ marginBottom: '2rem' }}>
        <h2 style={{ fontFamily: 'var(--font-headline)', fontSize: '1.125rem', marginBottom: '1rem', paddingBottom: '0.75rem', borderBottom: '2px solid var(--color-text-primary)' }}>
          Agent Logs (Latest)
        </h2>
        {logs.length === 0 ? (
          <p style={{ color: 'var(--color-text-muted)', fontSize: '0.85rem', padding: '1rem 0' }}>
            No agent logs yet. Run a generation cycle to see logs here.
          </p>
        ) : (
          <div style={{ maxHeight: '400px', overflowY: 'auto', fontFamily: 'monospace', fontSize: '0.75rem' }}>
            {logs.map((log) => (
              <div
                key={log.id}
                style={{
                  padding: '0.375rem 0.5rem',
                  borderBottom: '1px solid var(--color-border)',
                  display: 'flex',
                  gap: '0.75rem',
                  alignItems: 'flex-start',
                }}
              >
                <span style={{ color: 'var(--color-text-muted)', whiteSpace: 'nowrap', minWidth: '70px' }}>
                  {new Date(log.created_at).toLocaleTimeString()}
                </span>
                <span style={{
                  padding: '1px 6px',
                  borderRadius: '3px',
                  fontSize: '0.65rem',
                  fontWeight: 700,
                  minWidth: '40px',
                  textAlign: 'center',
                  background: log.level === 'ERROR' ? 'rgba(220,38,38,0.1)' : log.level === 'WARN' ? 'rgba(217,119,6,0.1)' : 'rgba(5,150,105,0.1)',
                  color: log.level === 'ERROR' ? '#DC2626' : log.level === 'WARN' ? '#D97706' : '#059669',
                }}>
                  {log.level}
                </span>
                <span style={{ padding: '1px 6px', background: 'var(--color-bg-secondary)', borderRadius: '3px', fontSize: '0.65rem', minWidth: '80px', textAlign: 'center' }}>
                  {log.agent_name}
                </span>
                <span style={{ flex: 1, color: 'var(--color-text-primary)', wordBreak: 'break-word' }}>
                  {log.message}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Posts */}
      <div className="admin-card">
        <h2 style={{ fontFamily: 'var(--font-headline)', fontSize: '1.125rem', marginBottom: '1rem', paddingBottom: '0.75rem', borderBottom: '2px solid var(--color-text-primary)' }}>
          All Posts ({posts.length})
        </h2>
        {posts.length === 0 ? (
          <p style={{ color: 'var(--color-text-muted)', fontSize: '0.85rem', padding: '1rem 0', textAlign: 'center' }}>
            No posts yet. Hit &quot;Generate Now&quot; to create one!
          </p>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table className="admin-table">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Category</th>
                  <th>Published</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {posts.map((post) => (
                  <tr key={post.id}>
                    <td>
                      <Link href={`/post/${post.slug}`} style={{ color: 'var(--color-text-primary)', textDecoration: 'none', fontWeight: 500 }}>
                        {post.title.length > 60 ? post.title.slice(0, 60) + '…' : post.title}
                      </Link>
                    </td>
                    <td>
                      <span className={`category-badge category-badge-${post.category}`}>{post.category}</span>
                    </td>
                    <td style={{ color: 'var(--color-text-muted)', fontSize: '0.8rem' }}>
                      {new Date(post.createdAt).toLocaleDateString()}
                    </td>
                    <td>
                      <button onClick={() => handleDelete(post.slug)} style={{ color: '#DC2626', background: 'none', border: 'none', cursor: 'pointer', fontSize: '0.8rem' }}>
                        Delete
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
