'use client';

import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';

interface PostItem {
  id: string;
  title: string;
  slug: string;
  category: string;
  autoGenerated: boolean;
  createdAt: string;
}

interface Stats {
  total: number;
  autoCount: number;
  lastGeneration: string | null;
  scheduler: {
    running: boolean;
    lastRun: string | null;
    totalGenerated: number;
  };
}

export default function AdminPage() {
  const [loggedIn, setLoggedIn] = useState(false);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loginError, setLoginError] = useState('');
  const [stats, setStats] = useState<Stats | null>(null);
  const [posts, setPosts] = useState<PostItem[]>([]);
  const [generating, setGenerating] = useState(false);
  const [message, setMessage] = useState('');

  const fetchData = useCallback(async () => {
    try {
      const [statsRes, postsRes] = await Promise.all([
        fetch('/api/admin'),
        fetch('/api/posts?limit=50'),
      ]);

      if (statsRes.ok) {
        setStats(await statsRes.json());
      }
      if (postsRes.ok) {
        const data = await postsRes.json();
        setPosts(data.posts || []);
      }
    } catch (err) {
      console.error('Failed to fetch data:', err);
    }
  }, []);

  useEffect(() => {
    if (loggedIn) {
      fetchData();
      const interval = setInterval(fetchData, 30000);
      return () => clearInterval(interval);
    }
  }, [loggedIn, fetchData]);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoginError('');

    try {
      const res = await fetch('/api/auth', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password }),
      });

      if (res.ok) {
        setLoggedIn(true);
      } else {
        setLoginError('Invalid credentials');
      }
    } catch {
      setLoginError('Login failed');
    }
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setMessage('');

    try {
      const res = await fetch('/api/generate', { method: 'POST' });
      const data = await res.json();

      if (data.success) {
        setMessage(`✅ ${data.message}`);
        fetchData();
      } else {
        setMessage(`❌ ${data.message || 'Generation failed'}`);
      }
    } catch {
      setMessage('❌ Failed to generate content');
    } finally {
      setGenerating(false);
    }
  };

  const handleToggleScheduler = async () => {
    try {
      const res = await fetch('/api/scheduler', { method: 'POST' });
      const data = await res.json();
      setMessage(data.running ? '▶️ Scheduler started' : '⏸ Scheduler paused');
      fetchData();
    } catch {
      setMessage('❌ Failed to toggle scheduler');
    }
  };

  const handleDelete = async (slug: string) => {
    if (!confirm('Are you sure you want to delete this post?')) return;

    try {
      const res = await fetch(`/api/posts/${slug}`, { method: 'DELETE' });
      if (res.ok) {
        setMessage('🗑️ Post deleted');
        fetchData();
      } else {
        setMessage('❌ Failed to delete post');
      }
    } catch {
      setMessage('❌ Failed to delete post');
    }
  };

  if (!loggedIn) {
    return (
      <div className="mx-auto max-w-md px-4 py-20">
        <h1 className="text-2xl font-bold text-gray-900 mb-6 text-center">Admin Login</h1>

        <form onSubmit={handleLogin} className="space-y-4">
          <div>
            <label htmlFor="username" className="block text-sm font-medium text-gray-700 mb-1">
              Username
            </label>
            <input
              id="username"
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm text-gray-900"
              required
            />
          </div>
          <div>
            <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">
              Password
            </label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm text-gray-900"
              required
            />
          </div>

          {loginError && <p className="text-red-600 text-sm">{loginError}</p>}

          <button
            type="submit"
            className="w-full rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700"
          >
            Login
          </button>
        </form>

        <p className="mt-4 text-xs text-gray-400 text-center">
          Default: admin / admin123 (set in .env)
        </p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Admin Dashboard</h1>

      {message && (
        <div className="mb-6 rounded-md bg-gray-100 p-4 text-sm text-gray-800">{message}</div>
      )}

      {/* Stats cards */}
      {stats && (
        <div className="grid gap-4 md:grid-cols-4 mb-8">
          <div className="rounded-lg border border-gray-200 bg-white p-6">
            <p className="text-sm text-gray-500">Total Posts</p>
            <p className="text-3xl font-bold text-gray-900">{stats.total}</p>
          </div>
          <div className="rounded-lg border border-gray-200 bg-white p-6">
            <p className="text-sm text-gray-500">Auto Generated</p>
            <p className="text-3xl font-bold text-green-600">{stats.autoCount}</p>
          </div>
          <div className="rounded-lg border border-gray-200 bg-white p-6">
            <p className="text-sm text-gray-500">Last Generation</p>
            <p className="text-sm font-medium text-gray-900 mt-1">
              {stats.lastGeneration
                ? new Date(stats.lastGeneration).toLocaleString()
                : 'Never'}
            </p>
          </div>
          <div className="rounded-lg border border-gray-200 bg-white p-6">
            <p className="text-sm text-gray-500">Scheduler</p>
            <p
              className={`text-lg font-bold ${
                stats.scheduler.running ? 'text-green-600' : 'text-red-600'
              }`}
            >
              {stats.scheduler.running ? '▶️ Running' : '⏸ Paused'}
            </p>
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="flex gap-4 mb-8">
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-500 disabled:opacity-50"
        >
          {generating ? '⏳ Generating...' : '✨ Generate Now'}
        </button>
        <button
          onClick={handleToggleScheduler}
          className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
        >
          {stats?.scheduler.running ? '⏸ Pause Automation' : '▶️ Start Automation'}
        </button>
      </div>

      {/* Posts list */}
      <div className="rounded-lg border border-gray-200 bg-white">
        <div className="border-b border-gray-200 px-6 py-4">
          <h2 className="text-lg font-semibold text-gray-900">All Posts</h2>
        </div>
        <div className="divide-y divide-gray-200">
          {posts.length === 0 ? (
            <div className="px-6 py-8 text-center text-gray-500">No posts yet</div>
          ) : (
            posts.map((post) => (
              <div key={post.id} className="flex items-center justify-between px-6 py-4">
                <div className="min-w-0 flex-1">
                  <Link
                    href={`/post/${post.slug}`}
                    className="text-sm font-medium text-gray-900 hover:text-blue-600 truncate block"
                  >
                    {post.title}
                  </Link>
                  <div className="flex items-center gap-2 mt-1">
                    <span
                      className={`text-xs px-2 py-0.5 rounded-full ${
                        post.category === 'blog'
                          ? 'bg-blue-100 text-blue-700'
                          : 'bg-red-100 text-red-700'
                      }`}
                    >
                      {post.category}
                    </span>
                    {post.autoGenerated && (
                      <span className="text-xs text-green-600">🤖 Auto</span>
                    )}
                    <span className="text-xs text-gray-400">
                      {new Date(post.createdAt).toLocaleString()}
                    </span>
                  </div>
                </div>
                <button
                  onClick={() => handleDelete(post.slug)}
                  className="ml-4 text-sm text-red-600 hover:text-red-800"
                >
                  Delete
                </button>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
