import Link from 'next/link';
import { Post } from '@/types';
import { formatDate, getCategoryMeta, getPostQualityScore, getReadingTime } from '@/lib/postPresentation';

function getCategoryBadgeClass(category: string): string {
  const map: Record<string, string> = {
    blog: 'badge-blog',
    news: 'badge-news',
    tech: 'badge-tech',
    business: 'badge-business',
    sports: 'badge-sports',
    ai: 'badge-ai',
  };
  return map[category] || 'badge-blog';
}

export default function PostCard({
  post,
  index = 0,
  reason,
  compact = false,
}: {
  post: Post;
  index?: number;
  reason?: string;
  compact?: boolean;
}) {
  const readingTime = getReadingTime(post.content);
  const meta = getCategoryMeta(post.category);
  const qualityScore = getPostQualityScore(post);

  return (
    <article
      className="card-gradient animate-fade-in-up"
      style={{
        opacity: 0,
        animationDelay: `${index * 0.08}s`,
        animationFillMode: 'forwards',
      }}
    >
      <div
        className={compact ? 'p-5' : 'p-6'}
        style={{
          background: 'var(--bg-card)',
          borderRadius: 'var(--radius-lg)',
          transition: 'all 0.3s ease',
        }}
      >
        <div className="flex items-center gap-2 mb-3 flex-wrap">
          <span className={`badge ${getCategoryBadgeClass(post.category)}`}>
            {meta.icon} {meta.label}
          </span>
          {post.autoGenerated && <span className="badge badge-auto">AI Assisted</span>}
          {post.sourceReferences.length > 0 && (
            <span className="badge badge-source">Sources {post.sourceReferences.length}</span>
          )}
          <span
            className="ml-auto flex items-center gap-1"
            style={{ color: 'var(--text-muted)', fontSize: '0.75rem' }}
          >
            <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            {readingTime} min read
          </span>
        </div>

        {reason && <p className="personal-reason">{reason}</p>}

        <Link href={`/post/${post.slug}`}>
          <h2
            className="text-lg font-semibold mb-2 transition-colors duration-200 line-clamp-2"
            style={{ color: 'var(--text-primary)' }}
          >
            {post.title}
          </h2>
        </Link>

        <p
          className={`text-sm mb-4 ${compact ? 'line-clamp-2' : 'line-clamp-3'}`}
          style={{ color: 'var(--text-secondary)', lineHeight: '1.6' }}
        >
          {post.summary}
        </p>

        <div className="flex items-center justify-between gap-3">
          <div className="flex flex-wrap gap-1.5">
            {post.tags.slice(0, compact ? 2 : 3).map((tag) => (
              <span
                key={tag}
                className="px-2 py-0.5 rounded text-xs"
                style={{
                  background: 'rgba(255, 255, 255, 0.05)',
                  color: 'var(--text-muted)',
                  fontSize: '0.7rem',
                }}
              >
                #{tag}
              </span>
            ))}
            <span
              className="px-2 py-0.5 rounded text-xs"
              style={{
                background: qualityScore >= 75 ? 'rgba(16, 185, 129, 0.12)' : 'rgba(245, 158, 11, 0.12)',
                color: qualityScore >= 75 ? '#34d399' : '#fbbf24',
                fontSize: '0.7rem',
              }}
            >
              Q{qualityScore}
            </span>
          </div>
          <time className="text-xs flex-shrink-0" style={{ color: 'var(--text-muted)' }}>
            {formatDate(post.createdAt)}
          </time>
        </div>
      </div>
    </article>
  );
}
