import Link from 'next/link';
import { Post } from '@/types';

export default function PostCard({ post }: { post: Post }) {
  return (
    <article className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm hover:shadow-md transition-shadow">
      <div className="flex items-center gap-2 mb-3">
        <span
          className={`inline-block rounded-full px-2.5 py-0.5 text-xs font-medium ${
            post.category === 'blog'
              ? 'bg-blue-100 text-blue-800'
              : 'bg-red-100 text-red-800'
          }`}
        >
          {post.category === 'blog' ? '📝 Blog' : '📰 News'}
        </span>
        {post.autoGenerated && (
          <span className="inline-block rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-medium text-green-800">
            🤖 Auto Generated
          </span>
        )}
      </div>

      <Link href={`/post/${post.slug}`}>
        <h2 className="text-xl font-semibold text-gray-900 hover:text-blue-600 transition-colors mb-2">
          {post.title}
        </h2>
      </Link>

      <p className="text-gray-600 text-sm mb-4 line-clamp-3">{post.summary}</p>

      <div className="flex items-center justify-between">
        <div className="flex flex-wrap gap-1">
          {post.tags.slice(0, 3).map((tag) => (
            <span key={tag} className="rounded bg-gray-100 px-2 py-0.5 text-xs text-gray-600">
              {tag}
            </span>
          ))}
        </div>
        <time className="text-xs text-gray-400">
          {new Date(post.createdAt).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
          })}
        </time>
      </div>
    </article>
  );
}
