import Link from 'next/link';
import { Post } from '@/types';
import { formatDate, getCategoryMeta, getReadingTime } from '@/lib/postPresentation';

function getCategoryBadgeClass(category: string): string {
  const map: Record<string, string> = {
    ai: 'category-badge-ai',
    tech: 'category-badge-tech',
    startups: 'category-badge-startups',
    research: 'category-badge-research',
    products: 'category-badge-products',
    blog: 'category-badge-blog',
    news: 'category-badge-news',
    business: 'category-badge-business',
    general: 'category-badge-general',
  };
  return map[category] || 'category-badge-general';
}

export default function PostCard({
  post,
  index = 0,
  compact = false,
}: {
  post: Post;
  index?: number;
  compact?: boolean;
}) {
  const readingTime = getReadingTime(post.content);
  const meta = getCategoryMeta(post.category);

  return (
    <article
      className="article-card animate-fade-in-up"
      style={{
        opacity: 0,
        animationDelay: `${index * 0.06}s`,
        animationFillMode: 'forwards',
      }}
    >
      <div className="article-card-body">
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
          <span className={`category-badge ${getCategoryBadgeClass(post.category)}`}>
            {meta.label}
          </span>
          {post.autoGenerated && (
            <span style={{ fontSize: '0.65rem', color: 'var(--color-text-muted)' }}>AI</span>
          )}
          <span style={{ marginLeft: 'auto', fontSize: '0.75rem', color: 'var(--color-text-muted)' }}>
            {readingTime} min
          </span>
        </div>

        <Link href={`/post/${post.slug}`}>
          <h2 className="article-card-title" style={{ marginBottom: '0.5rem' }}>
            {post.title}
          </h2>
        </Link>

        <p
          className={compact ? 'line-clamp-2' : 'line-clamp-3'}
          style={{ fontSize: '0.875rem', color: 'var(--color-text-secondary)', lineHeight: '1.5', marginBottom: '0.75rem' }}
        >
          {post.summary}
        </p>

        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', gap: '0.375rem', flexWrap: 'wrap' }}>
            {post.tags.slice(0, compact ? 2 : 3).map((tag) => (
              <span
                key={tag}
                style={{
                  fontSize: '0.7rem',
                  color: 'var(--color-text-muted)',
                }}
              >
                #{tag}
              </span>
            ))}
          </div>
          <time style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)', flexShrink: 0 }}>
            {formatDate(post.createdAt)}
          </time>
        </div>
      </div>
    </article>
  );
}
