export interface Post {
  id: string;
  title: string;
  slug: string;
  content: string;
  summary: string;
  tags: string[];
  category: string;
  metaDescription: string;
  createdAt: string;
  updatedAt: string;
  sourceReferences: string[];
  autoGenerated: boolean;
}

export interface PostRow {
  id: string;
  title: string;
  slug: string;
  content: string;
  summary: string;
  tags: string;
  category: string;
  metaDescription: string;
  createdAt: string;
  updatedAt: string;
  sourceReferences: string;
  autoGenerated: number;
}

export interface ResearchResult {
  topic: string;
  headline: string;
  summary: string;
  keyPoints: string[];
  references: string[];
}

export interface BlogContent {
  title: string;
  slug: string;
  metaDescription: string;
  content: string;
  summary: string;
  tags: string[];
}

export interface NewsContent {
  title: string;
  slug: string;
  metaDescription: string;
  content: string;
  summary: string;
  tags: string[];
}

export interface SchedulerStatus {
  running: boolean;
  lastRun: string | null;
  totalGenerated: number;
}
