import { getPersonalizedRecommendations } from '@/agents/recommendationAgent';
import { Post } from '@/types';

function post(overrides: Partial<Post>): Post {
  return {
    id: overrides.id || 'post-id',
    title: overrides.title || 'Untitled',
    slug: overrides.slug || 'untitled',
    content: overrides.content || '<p>Article body with enough content for testing.</p>',
    summary: overrides.summary || 'A useful summary for the article.',
    tags: overrides.tags || [],
    category: overrides.category || 'general',
    metaDescription: overrides.metaDescription || 'Meta description for the article.',
    createdAt: overrides.createdAt || new Date().toISOString(),
    updatedAt: overrides.updatedAt || new Date().toISOString(),
    sourceReferences: overrides.sourceReferences || [],
    autoGenerated: overrides.autoGenerated ?? true,
  };
}

describe('getPersonalizedRecommendations', () => {
  it('ranks matching category and topic posts first', () => {
    const posts = [
      post({
        id: '1',
        title: 'AI chips reshape cloud infrastructure',
        slug: 'ai-chips',
        category: 'ai',
        tags: ['chips', 'cloud'],
        sourceReferences: ['source'],
      }),
      post({
        id: '2',
        title: 'Sports media rights update',
        slug: 'sports-rights',
        category: 'sports',
        tags: ['media'],
      }),
    ];

    const results = getPersonalizedRecommendations({
      posts,
      topics: ['chips'],
      categories: ['ai'],
      limit: 2,
    });

    expect(results[0].slug).toBe('ai-chips');
    expect(results[0].reason).toContain('matches ai');
    expect(results[0].reason).toContain('mentions chips');
  });

  it('excludes dismissed slugs', () => {
    const results = getPersonalizedRecommendations({
      posts: [
        post({ slug: 'keep', category: 'ai', tags: ['agents'] }),
        post({ slug: 'hide', category: 'ai', tags: ['agents'] }),
      ],
      topics: ['agents'],
      categories: ['ai'],
      excludeSlugs: ['hide'],
      limit: 5,
    });

    expect(results.map((item) => item.slug)).toEqual(['keep']);
  });
});
