import { NextRequest, NextResponse } from 'next/server';
import { verifyToken } from '@/lib/auth';
import { getAllPosts } from '@/db/posts';
import { listUsers } from '@/db/users';
import { getSystemUsageSummary } from '@/db/usage';
import { getRecentAuditEntries } from '@/db/auditLog';

type ExportFormat = 'json' | 'csv';

function toCsv(rows: Record<string, unknown>[]): string {
  if (rows.length === 0) return '';
  const keys = Object.keys(rows[0]);
  const header = keys.join(',');
  const body = rows.map((row) =>
    keys
      .map((k) => {
        const val = row[k];
        if (val === null || val === undefined) return '';
        const str = typeof val === 'object' ? JSON.stringify(val) : String(val);
        return `"${str.replace(/"/g, '""')}"`;
      })
      .join(','),
  );
  return [header, ...body].join('\n');
}

// GET /api/export?type=<posts|users|usage|audit>&format=<json|csv> — data export (admin only)
export async function GET(request: NextRequest) {
  try {
    const token = request.cookies.get('admin_token')?.value;
    if (!token || !verifyToken(token)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const type = searchParams.get('type') || 'posts';
    const format = (searchParams.get('format') || 'json') as ExportFormat;

    if (!['json', 'csv'].includes(format)) {
      return NextResponse.json({ error: 'Invalid format. Use json or csv' }, { status: 400 });
    }

    let data: Record<string, unknown>[] = [];
    let filename = `export-${type}-${new Date().toISOString().slice(0, 10)}`;

    if (type === 'posts') {
      const { posts } = getAllPosts(1, 10_000);
      data = posts.map((p) => ({
        id: p.id,
        title: p.title,
        slug: p.slug,
        category: p.category,
        summary: p.summary,
        tags: p.tags.join(', '),
        autoGenerated: p.autoGenerated,
        createdAt: p.createdAt,
        updatedAt: p.updatedAt,
      }));
      filename = `posts-${new Date().toISOString().slice(0, 10)}`;
    } else if (type === 'users') {
      const { users } = listUsers(1, 10_000);
      data = users.map((u) => {
        const safe: Record<string, unknown> = { ...u };
        delete safe['passwordHash'];
        return safe;
      });
      filename = `users-${new Date().toISOString().slice(0, 10)}`;
    } else if (type === 'usage') {
      const summary = getSystemUsageSummary(30);
      data = [summary as unknown as Record<string, unknown>];
      filename = `usage-summary-${new Date().toISOString().slice(0, 10)}`;
    } else if (type === 'audit') {
      const entries = getRecentAuditEntries(10_000);
      data = entries as unknown as Record<string, unknown>[];
      filename = `audit-log-${new Date().toISOString().slice(0, 10)}`;
    } else {
      return NextResponse.json(
        { error: 'Invalid type. Use posts, users, usage, or audit' },
        { status: 400 },
      );
    }

    if (format === 'csv') {
      const csv = toCsv(data);
      return new NextResponse(csv, {
        headers: {
          'Content-Type': 'text/csv; charset=utf-8',
          'Content-Disposition': `attachment; filename="${filename}.csv"`,
        },
      });
    }

    return new NextResponse(JSON.stringify({ type, count: data.length, data }, null, 2), {
      headers: {
        'Content-Type': 'application/json',
        'Content-Disposition': `attachment; filename="${filename}.json"`,
      },
    });
  } catch (error) {
    console.error('Error in export GET:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
