import { NextRequest, NextResponse } from 'next/server';
import { getAllPosts, getPostsByCategory } from '@/db/posts';

export const dynamic = 'force-dynamic';

/**
 * GET /api/export?format=json|txt&category=blog&limit=50
 *
 * Export posts as downloadable JSON or TXT files.
 */
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const format = searchParams.get('format') || 'json';
  const category = searchParams.get('category');
  const limit = Math.min(parseInt(searchParams.get('limit') || '100', 10), 500);

  // Fetch posts
  const result = category
    ? getPostsByCategory(category, 1, limit)
    : getAllPosts(1, limit);

  const { posts } = result;

  if (format === 'txt') {
    // --- Plain text export ---
    const lines: string[] = [
      '═══════════════════════════════════════════════════════',
      '  AI Auto News — Exported Articles',
      `  Generated: ${new Date().toISOString()}`,
      `  Total Articles: ${posts.length}`,
      category ? `  Category: ${category}` : '',
      '═══════════════════════════════════════════════════════',
      '',
    ].filter(Boolean);

    for (const post of posts) {
      const plainContent = post.content.replace(/<[^>]*>/g, '').trim();
      lines.push(
        '───────────────────────────────────────────────────────',
        `📌 ${post.title}`,
        `Category: ${post.category} | Tags: ${post.tags.join(', ')}`,
        `Published: ${new Date(post.createdAt).toLocaleString()}`,
        `Auto-generated: ${post.autoGenerated ? 'Yes' : 'No'}`,
        '',
        'Summary:',
        post.summary,
        '',
        'Content:',
        plainContent,
        '',
      );
    }

    lines.push('═══════════════════════════════════════════════════════');
    lines.push(`End of export — ${posts.length} articles`);

    const text = lines.join('\n');
    const filename = `ai-auto-news-export${category ? `-${category}` : ''}-${new Date().toISOString().slice(0, 10)}.txt`;

    return new NextResponse(text, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  }

  // --- JSON export (default) ---
  const exportData = {
    exportedAt: new Date().toISOString(),
    totalArticles: posts.length,
    category: category || 'all',
    articles: posts.map((post) => ({
      id: post.id,
      title: post.title,
      slug: post.slug,
      category: post.category,
      summary: post.summary,
      content: post.content,
      tags: post.tags,
      autoGenerated: post.autoGenerated,
      createdAt: post.createdAt,
      updatedAt: post.updatedAt,
      sourceReferences: post.sourceReferences,
    })),
  };

  const json = JSON.stringify(exportData, null, 2);
  const filename = `ai-auto-news-export${category ? `-${category}` : ''}-${new Date().toISOString().slice(0, 10)}.json`;

  return new NextResponse(json, {
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  });
}
