import { Post } from '@/types';

export interface CategoryMeta {
  label: string;
  icon: string;
  color: string;
  description: string;
}

export interface TrustSignal {
  label: string;
  value: string;
  tone: 'good' | 'warn' | 'neutral';
}

export const CATEGORY_META: Record<string, CategoryMeta> = {
  ai: {
    label: 'AI',
    icon: 'AI',
    color: '#c084fc',
    description: 'Artificial intelligence research, tools, policy, and applied systems.',
  },
  tech: {
    label: 'Tech',
    icon: 'TECH',
    color: '#22d3ee',
    description: 'Engineering, platforms, devices, software, and product shifts.',
  },
  business: {
    label: 'Business',
    icon: 'BIZ',
    color: '#fbbf24',
    description: 'Markets, startups, strategy, funding, and company moves.',
  },
  sports: {
    label: 'Sports',
    icon: 'SPORT',
    color: '#34d399',
    description: 'Sports innovation, media, analytics, and performance technology.',
  },
  news: {
    label: 'News',
    icon: 'NEWS',
    color: '#f87171',
    description: 'Fresh updates and fast-moving developments across the feed.',
  },
  blog: {
    label: 'Blog',
    icon: 'BLOG',
    color: '#60a5fa',
    description: 'Longer reads, explainers, and analysis from the automated newsroom.',
  },
  general: {
    label: 'General',
    icon: 'INFO',
    color: '#94a3b8',
    description: 'Useful updates that do not fit a narrower section yet.',
  },
};

export const FEATURED_CATEGORY_ORDER = ['ai', 'tech', 'business', 'sports', 'news', 'blog'];

export function getCategoryMeta(category: string): CategoryMeta {
  const key = category.toLowerCase();
  if (CATEGORY_META[key]) return CATEGORY_META[key];
  return {
    label: key.charAt(0).toUpperCase() + key.slice(1),
    icon: key.slice(0, 4).toUpperCase() || 'INFO',
    color: '#94a3b8',
    description: `Latest ${key} coverage and related updates.`,
  };
}

export function getReadingTime(content: string): number {
  const text = content.replace(/<[^>]*>/g, '');
  const words = text.split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.ceil(words / 200));
}

export function formatDate(date: string): string {
  return new Date(date).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

export function timeAgo(isoDate: string): string {
  const diff = Date.now() - new Date(isoDate).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'Just now';
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

export function getTrustSignals(post: Post): TrustSignal[] {
  const hasReferences = post.sourceReferences.length > 0;
  const hasSummary = post.summary.trim().length > 40;
  const hasMeta = post.metaDescription.trim().length > 40;

  return [
    {
      label: 'Sources',
      value: hasReferences ? `${post.sourceReferences.length} listed` : 'Not listed',
      tone: hasReferences ? 'good' : 'warn',
    },
    {
      label: 'Disclosure',
      value: post.autoGenerated ? 'AI generated' : 'Editorial',
      tone: post.autoGenerated ? 'neutral' : 'good',
    },
    {
      label: 'Quality',
      value: hasSummary && hasMeta ? 'Ready' : 'Needs review',
      tone: hasSummary && hasMeta ? 'good' : 'warn',
    },
  ];
}

export function getPostQualityScore(post: Post): number {
  let score = 40;
  if (post.summary.trim().length >= 80) score += 15;
  if (post.metaDescription.trim().length >= 80) score += 15;
  if (post.tags.length >= 3) score += 10;
  if (post.sourceReferences.length > 0) score += 15;
  if (post.content.replace(/<[^>]*>/g, '').split(/\s+/).length >= 400) score += 5;
  return Math.min(score, 100);
}

export function groupPostsByCategory(posts: Post[], categories: string[]): { category: string; posts: Post[] }[] {
  const available = new Set([...categories, ...posts.map((post) => post.category)]);
  const ordered = [
    ...FEATURED_CATEGORY_ORDER.filter((category) => available.has(category)),
    ...Array.from(available).filter((category) => !FEATURED_CATEGORY_ORDER.includes(category)).sort(),
  ];

  return ordered
    .map((category) => ({
      category,
      posts: posts.filter((post) => post.category === category).slice(0, 4),
    }))
    .filter((section) => section.posts.length > 0);
}
